name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    steps:
      - name: 23f1003132@ds.study.iitm.ac.in
        run: echo "Hello, world!"
